server:
  port: 9191
spring:
  kafka:
    producer:
      bootstrap-servers: kafka.workiniot.com:9092
      group-id: customer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


